/* DO NOT EDIT THIS FILE - it is machine generated */
#include <jni.h>
/* Header for class com_den_4_inotify_java_NativeInotify */

#ifndef _Included_com_den_4_inotify_java_NativeInotify
#define _Included_com_den_4_inotify_java_NativeInotify
#ifdef __cplusplus
extern "C" {
#endif
/*
 * Class:     com_den_4_inotify_java_NativeInotify
 * Method:    init
 * Signature: ()I
 */
JNIEXPORT jint JNICALL Java_com_den_14_inotify_1java_NativeInotify_init
  (JNIEnv *, jobject);

/*
 * Class:     com_den_4_inotify_java_NativeInotify
 * Method:    close
 * Signature: (I)V
 */
JNIEXPORT void JNICALL Java_com_den_14_inotify_1java_NativeInotify_close
  (JNIEnv *, jobject, jint);

/*
 * Class:     com_den_4_inotify_java_NativeInotify
 * Method:    add_watch
 * Signature: (ILjava/lang/String;I)I
 */
JNIEXPORT jint JNICALL Java_com_den_14_inotify_1java_NativeInotify_add_1watch
  (JNIEnv *, jobject, jint, jstring, jint);

/*
 * Class:     com_den_4_inotify_java_NativeInotify
 * Method:    rm_watch
 * Signature: (II)I
 */
JNIEXPORT jint JNICALL Java_com_den_14_inotify_1java_NativeInotify_rm_1watch
  (JNIEnv *, jobject, jint, jint);

/*
 * Class:     com_den_4_inotify_java_NativeInotify
 * Method:    read
 * Signature: (I)V
 */
JNIEXPORT void JNICALL Java_com_den_14_inotify_1java_NativeInotify_read
  (JNIEnv *, jobject, jint);

#ifdef __cplusplus
}
#endif
#endif
